DROP DATABASE IF EXISTS `pfquest`;
DROP DATABASE IF EXISTS `vmangos`;

SET GLOBAL validate_password.policy=LOW;
SET GLOBAL validate_password.length=0;

DROP USER IF EXISTS 'mangos'@'localhost';
CREATE USER 'mangos'@'localhost' IDENTIFIED BY 'mangos';

CREATE DATABASE `pfquest` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES, EXECUTE, ALTER ROUTINE, CREATE ROUTINE ON `pfquest`.* TO 'mangos'@'localhost';

CREATE DATABASE `vmangos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES, EXECUTE, ALTER ROUTINE, CREATE ROUTINE ON `vmangos`.* TO 'mangos'@'localhost';
